core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from crud_rest_framework.urls import router

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("apps.home_page.urls")),
    path("greetings/", include("greetings.urls")),
    path("users/", include("users_generator.urls")),
    path("contacts/", include("contacts.urls")),
    path("sessions/", include("session.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("accounts/", include("users.urls")),
    path("middleware/", include("middlewares.urls")),
    path("api-drf/", include(router.urls)),
    path("api-drf/", include("crud_rest_framework.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

middlewares/urls.py
from django.urls import path

from middlewares import views

app_name = "middlewares"

urlpatterns = [
    path("", views.MiddlewaresView.as_view(), name="index"),
    path("info/", views.AllRequestInfoView.as_view(), name="all_info"),
    path("session/<slug:session_key>/", views.CurrentRequestInfoView.as_view(), name="session_info"),
    path("user/<int:pk>/", views.CurrentUserInfoView.as_view(), name="user_info"),
]

session/urls.py
from django.urls import path

from session import views


app_name = "session"

urlpatterns = [path("", views.session_info, name="session")]

middlewares/models.py
from django.conf import settings
from django.db import models


class VisitorsRequests(models.Model):
    session_key = models.CharField(max_length=255)
    path = models.SlugField(max_length=255)
    count_of_visits = models.IntegerField()
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True)
    last_visit_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "Visit Info"

middlewares/views.py
from django.views.generic import TemplateView, ListView
from middlewares.models import VisitorsRequests
from middlewares.services.aggregations import aggregator


class MiddlewaresView(TemplateView):
    template_name = "middlewares/home_page.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Middleware"
        return context


class AllRequestInfoView(ListView):
    model = VisitorsRequests
    template_name = "middlewares/all_sessions.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "All Sessions"
        session_request = VisitorsRequests.objects.all()
        context["object_list"] = session_request
        context.update(aggregator(session_request))
        return context


class CurrentRequestInfoView(ListView):
    model = VisitorsRequests
    template_name = "middlewares/current_session.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Current session info"
        session_request = VisitorsRequests.objects.filter(session_key=self.kwargs["session_key"])
        context["object_list"] = session_request
        context.update(aggregator(session_request))
        return context


class CurrentUserInfoView(ListView):
    model = VisitorsRequests
    template_name = "middlewares/current_user.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Current user info"
        session_request = VisitorsRequests.objects.filter(user=self.kwargs["pk"])
        context["object_list"] = session_request
        context.update(aggregator(session_request))
        return context

session/views.py
import datetime

from django.core.handlers.wsgi import WSGIRequest
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render


def session_info(request: WSGIRequest | HttpRequest) -> HttpResponse:
    session = request.session
    if not session.session_key:
        session.save()
    visit_time = session.get("visit_time", datetime.datetime.now())
    count_of_visits = session.get("count", 0)
    count_of_visits += 1
    session["count"] = count_of_visits
    return render(
        request,
        "session/index.html",
        {
            "title": "Session info",
            "session_id": session.session_key,
            "count_of_visits": count_of_visits,
            "visit_time": visit_time,
        },
    )

templates/middlewares/_helpers/nav_middleware.html
<ul class="nav justify-content-center">
    <li class="nav-item">
        <a class="nav-link active" aria-current="page" href="{% url 'middlewares:all_info' %}">All info about actions</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'middlewares:session_info' request.session.session_key %}">Info about
            current session actions</a>
    </li>
    </li>
    {% if user.is_authenticated %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'middlewares:user_info' user.pk %}">Info about current user
                actions</a>
        </li>
    {% endif %}
</ul>

templates/middlewares/_helpers/sessions.html
<h3>Total count of visits : {{ total_visits }}. Total visited pages: {{ count_of_visited_pages }}</h3>
<table class="table">
    <thead>
    <tr>
        <th scope="col">User</th>
        <th scope="col">Session key</th>
        <th scope="col">Path</th>
        <th scope="col">Visits_count</th>
        <th scope="col">Last time visit</th>
    </tr>
    </thead>
    <tbody>
    {% for session in object_list %}
        <tr>
            {% if user.is_authenticated %}
                <td>{{ session.user }}</td>
            {% else %}
                <td>Anonymous</td>
            {% endif %}
            <td>{{ session.session_key }}</td>
            <td>{{ session.path }}</td>
            <td>{{ session.visits_count }}</td>
            <td>{{ session.last_visit_at }}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>