contacts/urls.py
from django.urls import path

from . import views

app_name = "contacts"

urlpatterns = [
    path("", views.ContactListView.as_view(), name="index"),
    path("add-contact/", views.ContactCreateView.as_view(), name="add_contact"),
    path("search-contact/", views.search_contact, name="contact_search"),
    path("view-contact/", views.show_contact_search, name="contact_info"),
    path("delete-contact/<int:pk>/", views.ContactDeleteView.as_view(), name="contact_delete"),
    path("contact/contact-update/<int:pk>/", views.ContactUpdateView.as_view(), name="contact_update"),
    path("contact/<int:pk>/", views.ContactView.as_view(), name="contact"),
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from crud_rest_framework.urls import router

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("apps.home_page.urls")),
    path("greetings/", include("greetings.urls")),
    path("users/", include("users_generator.urls")),
    path("contacts/", include("contacts.urls")),
    path("sessions/", include("session.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("accounts/", include("users.urls")),
    path("middleware/", include("middlewares.urls")),
    path("api-drf/", include(router.urls)),
    path("api-drf/", include("crud_rest_framework.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

greetings/urls.py
from django.urls import path

from . import views

app_name = "greetings"

urlpatterns = [
    path("", views.greetings, name="index"),
    path("<str:name>", views.greetings, name="index"),
]

session/urls.py
from django.urls import path

from session import views


app_name = "session"

urlpatterns = [path("", views.session_info, name="session")]

users/urls.py
from django.urls import path

from . import views

app_name = "users"

urlpatterns = [
    path("signup/", views.UserSingUpView.as_view(), name="signup"),
    path("edit/<int:pk>/", views.UserUpdateView.as_view(), name="edit"),
]

templates/_header.html
{% load static %}

<header class="my-header">
    <div class="logo" >
        <img src="{% static 'images/logo.svg' %}" onclick="myFunction()"/>
    </div>
    <ul class="nav">
        <li class="nav">
            <h1><a class="nav-link" href="{% url 'home_page:index' %}">Home</a></h1>
        </li>
        <li class="nav">
            <h1><a class="nav-link" href="{% url 'greetings:index' %}">Greetings</a></h1>
        </li>
        <li class="nav">
            <h1><a class="nav-link" href="{% url 'users_generator:index' %}">Users</a></h1>
        </li>
        <li class="nav">
            <h1><a class="nav-link" href="{% url 'contacts:index' %}">Contacts</a></h1>
        </li>
        <li class="nav">
            <h1><a class="nav-link" href="{% url 'session:session' %}">Session info</a></h1>
        </li>
        {% if user.is_authenticated %}
            <li class="nav">
                <a class="nav-link" href="{% url 'users:edit' user.pk %}">Edit profile</a>
            </li>
            <li class="nav">
                <a class="nav-link" href="{% url 'logout' %}">Log out</a>
            </li>
            <li class="nav">
                <div class="card" style="width: 3em; height: 3em;">
            <img src="{{ user.avatar.url }}" class="user-avatar" alt="{{ user.username }}">
        </div>
            </li>
                    <li class="nav-item">
            <a class="nav-link" href="{% url 'middlewares:index' %}">Middleware</a>
            </li>
        {% endif %}
        <script>
        function myFunction() {
           var element = document.body;
           element.classList.toggle("dark-mode");
        }
        </script>
    </ul>
</header>

templates/base.html
{% load static %}
<body>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% if title %}
            {{ title }}
        {% else %}
            Home
        {% endif %}
        | Site
    </title>
    {#[connect_bootstrap] - [BEGIN] #}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    {#[connect_bootstrap] - [END] #}
    <link rel="shortcut icon" type="image/icon" href="{% static 'images/favicon.png' %}"/>
    <link
            href="{% static 'styles/index.css' %}"
            rel="stylesheet"
    >
</head>
<body>
{% include '_header.html' %}
{% if user.is_authenticated %}
{% else %}
    <p>You are not logged in.</p>
    <a class="btn btn-primary"
       href="{% url 'login' %}">Log In</a>
    <a class="btn btn-primary"
       href="{% url 'users:signup' %}">Registration</a>
{% endif %}
{% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li class="{{ message.tags }}">
                {{ message|safe }}
            </li>
        {% endfor %}
    </ul>
{% endif %}
{% block content %}
{% endblock %}

</div>
</body>
</html>
</body>