contacts/urls.py
from django.urls import path

from . import views

app_name = "contacts"

urlpatterns = [
    path("", views.ContactListView.as_view(), name="index"),
    path("add-contact/", views.ContactCreateView.as_view(), name="add_contact"),
    path("search-contact/", views.search_contact, name="contact_search"),
    path("view-contact/", views.show_contact_search, name="contact_info"),
    path("delete-contact/<int:pk>/", views.ContactDeleteView.as_view(), name="contact_delete"),
    path("contact/contact-update/<int:pk>/", views.ContactUpdateView.as_view(), name="contact_update"),
    path("contact/<int:pk>/", views.ContactView.as_view(), name="contact"),
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from crud_rest_framework.urls import router

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("apps.home_page.urls")),
    path("greetings/", include("greetings.urls")),
    path("users/", include("users_generator.urls")),
    path("contacts/", include("contacts.urls")),
    path("sessions/", include("session.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("accounts/", include("users.urls")),
    path("middleware/", include("middlewares.urls")),
    path("api-drf/", include(router.urls)),
    path("api-drf/", include("crud_rest_framework.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contacts/models.py
import uuid
from django.db import models
from django.urls import reverse


def get_icon_path(instance, filename) -> str:
    _, extension = filename.rsplit(".", maxsplit=1)
    return f"contacts/contact/avatar/{instance.pk}/{uuid.uuid4()}/avatar.{extension}"


class Contact(models.Model):
    name = models.CharField(max_length=255)
    phone = models.SlugField(max_length=60)
    b_day = models.DateField()
    created_at = models.DateField(auto_now_add=True)
    modified_at = models.DateField(auto_now=True)
    is_auto_generated = models.BooleanField(default=False)
    avatar = models.ImageField(
        max_length=255,
        blank=True,
        null=True,
        upload_to=get_icon_path,
    )

    def __str__(self):
        return f"{self.name} {self.phone} {self.b_day}"

    __repr__ = __str__

    def get_absolute_url(self):
        return reverse(
            "contacts:contact_update",
            kwargs={"pk": self.pk},
        )

    class Meta:
        ordering = ("-created_at",)
        verbose_name = "Contact"
        verbose_name_plural = "Contacts"

contacts/forms.py
from django import forms
from django.core.exceptions import ValidationError
from core import settings
from .models import Contact


class AddContactForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["b_day"].input = settings.DATE_INPUT_FORMATS
        self.fields["b_day"].help_txt = "format DD.MM.YYYY"
        self.fields["phone"].help_txt = "Enter phone number"

    class Meta:
        model = Contact
        fields = ("name", "phone", "b_day", "avatar")

    def clean_phone(self):
        phone = self.cleaned_data["phone"]
        if not phone.isdecimal():
            raise ValidationError("Invalid phone number(int only)")
        elif len(phone) != 10:
            raise ValidationError("Invalid phone number(enter UA number")
        elif not phone.startswith("0"):
            raise ValidationError("Invalid phone number(should starts with 0)")
        return phone

contacts/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpRequest
from django.utils.decorators import method_decorator
from django.views.generic import ListView, UpdateView, CreateView, DeleteView, TemplateView
from django.shortcuts import render
from contacts.models import Contact
from django.urls import reverse_lazy


class ContactListView(ListView):
    model = Contact


class ContactCreateView(CreateView):
    model = Contact
    fields = (
        "name",
        "phone",
        "b_day",
        "avatar",
    )

    def get_success_url(self):
        return reverse_lazy("contacts:contact", kwargs={"pk": self.object.pk})


def search_contact(request: HttpRequest) -> HttpResponse:
    return render(
        request,
        "contacts/search_contact.html",
        {
            "title": "Search Contact",
        },
    )


def show_contact_search(request: HttpRequest) -> HttpResponse:
    query = request.GET.get("q")
    if query.startswith("0"):
        contact = Contact.objects.get(phone=query)
    else:
        contact = Contact.objects.get(pk=query)
    return render(
        request,
        "contacts/show_contact_search.html",
        {
            "title": f"Show Contact {contact.name}",
        },
    )


@method_decorator(login_required, name="post")
class ContactDeleteView(DeleteView):
    model = Contact
    success_url = reverse_lazy("contacts:index")


@method_decorator(login_required, name="post")
class ContactUpdateView(UpdateView):
    model = Contact
    fields = (
        "name",
        "phone",
        "b_day",
        "avatar",
    )
    template_name_suffix = "_update_form"

    def get_success_url(self):
        contact_pk = self.kwargs["pk"]
        return reverse_lazy("contacts:contact", kwargs={"pk": contact_pk})


class ContactView(TemplateView):
    template_name = "contacts/show_contact_info.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        contact = Contact.objects.get(pk=context["pk"])
        context["contact"] = contact
        context["title"] = f"Info {contact.name}."
        return context

templates/contacts/contact_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
     {% include 'contacts/includes/navigation.html' %}


    <h1>{{ title }}</h1>

    <form method="POST" autocomplete="off" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.non_field_errors }}
        {{ form|crispy }}
        <input type="submit" class="btn btn-primary" value="Add user">
    </form>
{% endblock %}

templates/contacts/contact_list.html
{% extends "base.html" %}


{% block content %}

    {% include 'contacts/includes/navigation.html' %}

    <ol class="my-custom-list">
    {% for contact in object_list %}
        <li class="my-element-style" >
            <div>
                <div class="col">
                    {% if contact.avatar %}
                        <img class='contact-avatar' src="{{ contact.avatar.url}}" alt="{{ contact.name}}" />
                    {% endif %}
                    <p>Name: {{ contact.name }}</p>
                    <p>Phone: {{ contact.phone }}</p>
                    <p>Birth day: {{ contact.b_day|date:"D.M.Y" }}</p>
                    {% include 'contacts/includes/update.html' %}
                    {% include 'contacts/includes/delete.html' %}
                </div>
            </div>
            <hr>
            </li>
    {% endfor %}
    </ol>
{% endblock %}

templates/contacts/contact_update_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

    {% include 'contacts/includes/navigation.html' %}

    <h1>{{ title }}</h1>

    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.non_field_errors }}
        <div class="form-row">
            <div class="form-group col-md-6 mb-0">
                {{ form.name|as_crispy_field }}
            </div>
            <div class="form-group col-md-6 mb-0">
                {{ form.phone|as_crispy_field }}
            </div>
            <div class="form-group col-md-6 mb-0">
                {{ form.b_day|as_crispy_field }}
            </div>
            <div class="form-group col-md-6 mb-0">
                {{ form.avatar|as_crispy_field }}
            </div>
        </div>

        <input type="submit" class="btn btn-primary" value="Update user">
    </form>
    <a href="{% url 'contacts:index' %}"><- Back</a>
{% endblock %}

templates/contacts/index.html
{% extends "base.html" %}


{% block content %}

    {% include 'contacts/includes/navigation.html' %}

    <ol class="my-custom-list">
    {% for contact in contacts %}
        <li class="my-element-style" >
            <div>
                <div class="col">
                    <p>Name: {{ contact.name }}</p>
                    <p>Phone: {{ contact.phone }}</p>
                    <p>Birth day: {{ contact.b_day|date:"D.M.Y" }}</p>
                    {% include 'contacts/includes/update.html' %}
                    {% include 'contacts/includes/delete.html' %}
                </div>
            </div>
            <hr>
            </li>
    {% endfor %}
    </ol>
{% endblock %}

templates/contacts/search_contact.html
{% extends 'base.html' %}

{% block content %}

    {% include 'contacts/includes/navigation.html' %}

    <h1>{{ title }}</h1>
    <form action="{% url 'contacts:contact_search' %}" method="get">
        <label>
            <input name="q" type="text" placeholder="Enter phone number or ID">
        </label>
    </form>

{% endblock %}

templates/contacts/show_contact_info.html
{% extends 'base.html' %}

{% block content %}

    {% include 'contacts/includes/view.html' %}
    <a href="{% url 'contacts:index' %}"><- Back</a>

{% endblock %}

templates/contacts/show_contact_search.html
{% extends 'base.html' %}

{% block content %}

    {% include 'contacts/includes/view.html' %}
    <p><a href="{% url 'contacts:contact_search' %}"><- Back to search</a></p>

{% endblock %}

templates/contacts/update_contact.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

    {% include 'contacts/includes/navigation.html' %}

    <h1>{{ title }}</h1>

    <form method="POST" autocomplete="off" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.non_field_errors }}
        {{ form|crispy}}
        <input type="submit" class="btn btn-primary" value="Update user">
    </form>
    <a href="{% url 'contacts:index' %}"><- Back</a>
{% endblock %}